### ISSUE TITLE
Subnautica not starting 

### ISSUE THREAD

**Issue by Jaskalabomba** [toebeann/gib#4]
ma subnautica isn`t strting anymore after installing BepInEx, it is just stuck in a black screen with the subnautica curser. I can move the cursor around and the mac isn`t freezing or anything. The script said that everything went well nad BepInEx has been installed, but it ain`t working :(

**Comment by toebeann** [comment]
Can you please provide screenshots of the subnautica folder, and the steam launch options?

**Comment by toebeann** [comment]
However, if the script has said that BepInEx is working, that means it detected the BepInEx/LogOutput.log file getting created and edited by BepInEx, which indicates BepInEx is successfully injected into the game process, which means gib has done its job. 

If the game is taking a while to start with BepInEx installed, there is nothing gib can do about that.

BepInEx itself is pretty lightweight. The BepInEx pack for Subnautica does include some scripts that run before the game launches which, on slow machines, might make it take a little longer to start. However, these scripts are important for ensuring the mods work properly for you.

So, if you want the mods, then you need to be patient and let the scripts run, or, get a faster computer. On my 2019 MacBook Pro with the BepInEx pack for Subnautica, the game launches very quickly - I hardly notice a difference with or without BepInEx. 

So, perhaps you need a newer machine, or, maybe you just need to close some apps? Reboot?

**Comment by Jaskalabomba** [comment]
it is a MacBook Pro (13-inch, Late 2011), ant the only reason i want to mod the game is to install the performance mod because the hardware can bearly handel the game so that might be the problem.

**Comment by Jaskalabomba** [comment]
bearily is a bit harsh , i get like 15-20fps

**Comment by toebeann** [comment]
Right, but none of that changes anything about how _gib_ is affecting anything. You have BepInEx correctly installed, that is all that gib will do.

Whether or not you have poor performance with BepInEx installed after that _has nothing to do with using gib to install it_, and therefore opening an issue with _gib_ is not the path forward.

I have nothing to do with any mods claiming to increase your performance, so I cannot speak to whether they will have any impact on your start-up times, or your performance overall.

I would personally suggest testing with _just_ the BepInEx pack installed. If you are noticing a start-up performance impact with _just_ the BepInEx pack installed, then there's nothing anyone can do for you, you will just have to be patient and wait for it to load. It should not take long.

No matter how long it takes to load or whether the game _ever_ fully loads, if you have a LogOutput.log file being generated every time you run the game, the issue is _not_ with gib.

You may wish to inspect the contents of this `LogOutput.log` file to see if there is anything inside of it that might indicate an error. Please note that any errors indicated this file, once again, will have nothing to do with gib.

**Comment by toebeann** [comment]
If you are looking for a generalised place to get help with modding Subnautica, you should try [the Subnautica Modding discord server](https://discord.gg/UpWuWwq).

**Comment by Jaskalabomba** [comment]
Ok thx
