### ISSUE TITLE
Loops on "location of Unity game to install BepInEx

### ISSUE THREAD

**Issue by jbstavers** [toebeann/gib#6]
I am getting this request over and over again: 

Next, we need to know the location of the Unity game which you would like to install BepInEx to:

  1. Open the Finder window where your Unity game is located, find the app (e.g. Subnautica.app), select it and press ⌥ ⌘ C to copy the path to the app

  2. Then, press ⌘ V here to paste the path and press enter: 

I enter the following path, and it just gives me this instruction again
/Users/[MYUSERNAME]/Library/Application Support/Steam/steamapps/common/SubnauticaZero/SubnauticaZero.app

**Comment by toebeann** [comment]
It is looping because it has rejected your input.

Did you notice the Option symbol where it is telling you to copy? You need to use Option + Command + C to copy, Command + V to paste. The reason for this is because if you only use Command + C the format of the path is not as easy to parse, and I was too lazy to spend time on this when it is easier for you to press one extra button when copying ;)

**Comment by toebeann** [comment]
As it has been over a month with no comment from the original author of the issue, I'm going to go ahead and close this under the assumption that my assessment of this being a simple user error is correct :)

One day I would like to look into making this particular user error less common, but I don't currently have time.

**Comment by jbstavers** [comment]
Hi - sorry for not posting a response, I meant to, really! It actually 
turned out to be a problem with my Steam installation, I reinstalled 
Steam and the game and the install worked fine.
